# -*- coding: utf-8 -*-
"""Cricket Ball Detection and Tracking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbOWj03Z2FerUTFMA0zaz28w86Zpomd9
"""

# @title Cricket Ball Detection - Highlight Current Ball Only
# This version highlights the ball's CURRENT position with a green circle
# in every frame. It does NOT leave a trail/history behind.


!pip install ultralytics opencv-python-headless pandas numpy

import cv2
import numpy as np
import pandas as pd
from ultralytics import YOLO
import os


INPUT_VIDEO_PATH = "video.mp4"
MODEL_PATH = "best.pt"
OUTPUT_VIDEO_PATH = "output_highlighted_ball.mp4"
OUTPUT_CSV_PATH = "annotations.csv"


MISS_FRAMES_TOLERANCE = 5

class Tracker:
    def __init__(self, fps):
        self.kf = cv2.KalmanFilter(4, 2)
        self.kf.measurementMatrix = np.array([[1, 0, 0, 0], [0, 1, 0, 0]], np.float32)
        self.kf.transitionMatrix = np.array([[1, 0, 1, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]], np.float32)
        self.kf.processNoiseCov = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], np.float32) * 0.03

        self.predicted = np.zeros((2, 1), np.float32)
        self.is_initialized = False
        self.miss_count = 0

    def update(self, coord):
        if not self.is_initialized:
            self.kf.statePre = np.array([[coord[0]], [coord[1]], [0], [0]], np.float32)
            self.kf.statePost = np.array([[coord[0]], [coord[1]], [0], [0]], np.float32)
            self.predicted = np.array([[coord[0]], [coord[1]]], np.float32)
            self.is_initialized = True
        else:
            self.kf.correct(np.array([[coord[0]], [coord[1]]], np.float32))
            self.miss_count = 0

    def predict(self):
        if self.is_initialized:
            pred = self.kf.predict()
            self.predicted = pred[:2]
            return (int(self.predicted[0]), int(self.predicted[1]))
        return None


def main():
    if not os.path.exists(INPUT_VIDEO_PATH):
        print(f"Error: Input video '{INPUT_VIDEO_PATH}' not found.")
        return

    print(f"Loading model from {MODEL_PATH}...")
    try:
        model = YOLO(MODEL_PATH)
    except:
        print("Model load failed. Downloading YOLOv8n as fallback.")
        model = YOLO('yolov8n.pt')

    cap = cv2.VideoCapture(INPUT_VIDEO_PATH)
    width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps    = cap.get(cv2.CAP_PROP_FPS)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(OUTPUT_VIDEO_PATH, fourcc, fps, (width, height))

    tracker = Tracker(fps)
    csv_data = []

    print(f"Processing {total_frames} frames...")
    frame_idx = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # 1. Inference
        results = model.predict(frame, conf=0.25, verbose=False)[0]
        detected_ball = None

        # Filter strictly for ball classes
        target_ids = [id for id, name in model.names.items() if 'ball' in name.lower()]
        if not target_ids and 'sports ball' in model.names.values(): target_ids = [32]

        best_conf = 0
        for box in results.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            if (not target_ids) or (cls_id in target_ids):
                if conf > best_conf:
                    x1, y1, x2, y2 = map(int, box.xyxy[0])
                    cx, cy = (x1 + x2) // 2, (y1 + y2) // 2
                    detected_ball = (cx, cy)
                    best_conf = conf

        # 2. Update Tracker
        visible_flag = 0
        final_x, final_y = -1, -1

        if detected_ball:
            tracker.update(detected_ball)
            visible_flag = 1
            final_x, final_y = detected_ball
        else:
            pred = tracker.predict()
            if tracker.is_initialized and tracker.miss_count < MISS_FRAMES_TOLERANCE:
                tracker.miss_count += 1
            else:
                tracker.is_initialized = False

        csv_data.append([frame_idx, final_x, final_y, visible_flag])

        # 3. Draw Green Highlight on CURRENT Ball Position Only
        if visible_flag == 1 and final_x != -1:
            cv2.circle(frame, (final_x, final_y), 10, (0, 255, 0), -1)

        out.write(frame)
        frame_idx += 1

        if frame_idx % 50 == 0:
            print(f"Processed {frame_idx}/{total_frames} frames...")

    cap.release()
    out.release()

    df = pd.DataFrame(csv_data, columns=["frame", "x", "y", "visible"])
    df.to_csv(OUTPUT_CSV_PATH, index=False)

    print("\nProcessing Complete!")
    print(f"Video saved to: {OUTPUT_VIDEO_PATH}")

if __name__ == "__main__":
    main()